# Generated by Django 6.0.5 on 2026-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Активна'), ('done', 'Приключена')], default='open', max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Получаване')], max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.IntegerField(choices=[(10, 'Ниска'), (20, 'Нормална'), (30, 'Висока'), (40, 'Спешна')], default=20),
        ),
    ]
