# Generated by Django 6.0.5 on 2026-05-28 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_task_status_alter_task_type_alter_task_urgency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField()),
                ('contact_address', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Получаване')], default='pickup', max_length=16)),
                ('urgency', models.IntegerField(choices=[(10, 'Ниска'), (20, 'Нормална'), (30, 'Висока'), (40, 'Спешна')], default=20)),
                ('frequency', models.CharField(choices=[('daily', 'Всеки ден'), ('weekly', 'Всяка седмица')], default='daily', max_length=16)),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Понеделник'), (1, 'Вторник'), (2, 'Сряда'), (3, 'Четвъртък'), (4, 'Петък'), (5, 'Събота'), (6, 'Неделя')], null=True)),
                ('due_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_task_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['frequency', 'weekday', 'due_time', 'task_text'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='logistics.recurringtasktemplate'),
        ),
    ]
